name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install fpm
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential
          sudo gem install --no-document fpm
      - name: Build .deb from tag source
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          bash scripts/build_deb.sh "$VERSION"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb
          path: dist/*.deb
      - name: Upload .deb to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.deb

  build-sdist-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build sdist/wheel
        run: |
          python -m pip install --upgrade build
          python -m build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pypi-artifacts
          path: dist/*
